/**
* This class is created to store all constants
* 
* @author      Tejas Khamakar
**/
public class Einstein_GlobalConstants {
	public static final String AUTHORIZE_KEY_FILE_NAME = 'einstein_platform';
    public static final String KEY_CONTENT_BEGIN_RSA_PRIVATE_KEY = '-----BEGIN RSA PRIVATE KEY-----';
    public static final String KEY_CONTENT_END_RSA_PRIVATE_KEY = '-----END RSA PRIVATE KEY-----';
    public static final String NEW_LINE = '\n';
    public static final String RS_CODE = 'RS256';
    public static final String DEVELOPER_FORCE_COM = 'developer.force.com';
    public static final String REST_CONNECTION_TYPE_POST = 'POST';
    public static final String REST_CONNECTION_TYPE_GET = 'GET';
    public static final String REST_CONNECTION_TYPE_DELETE = 'DELETE';
    public static final String AUTHORIZATION = 'Authorization';
    public static final String BEARER = 'Bearer ';
    public static final String CONTENT_TYPE = 'Content-type';
    public static final String CONTENT_TYPE_APPLICATION_JSON = 'application/json';
    public static final String CACHE_CONTROL = 'Cache-Control';
    public static final String NO_CACHE = 'no-cache';
    public static final String HEADER_CONTENT_TYPE = 'Content-Type';
    public static final String PATH = 'path';
    public static final String FORM_BUILDER_TYPE = 'type';
    public static final String TEXT_INTENT = 'text-intent';
    public static final String DATASET_ID = '#DSID#';
    public static final String DELETION_ID = '#DELID#';
    public static final String NAME = 'name';
    public static final String CASE_ROUTING_MODEL = 'Case Routing Model - ';
    public static final String DATASET_ID_TEXT = 'datasetId';
    public static final String MODEL_ID = '#MODELID#';
    public static final String STATUS = 'status';
    public static final String FAILED = 'FAILED';
    public static final String KEY_FAILURE_MESSAGE = 'failureMsg';
    public static final String MODEL_ID_TEXT = 'modelId';
    public static final String DOCUMENT = 'document';
    public static final String BOUNDRY = '1ff13444ed8140c7a32fc4e6451aa76d';
    public static final String ACCESS_TOKEN_TEXT = 'access_token';
}