/**
* Name : LRC_Constants
* Description: This class will be used to maintain Constants
* @Date 09/07/2018
*/
public with sharing class LRC_Constants {
	public final static String GOOGLEAUTOCOMPLETEURL = System.Label.GoogleAutoCompleteURL;
    public final static String GOOGLEADDRESSDETAILSFROMPLACEIDURL = System.Label.GoogleAddressDetailsFromPlaceIdURL;
    public final static String GOOGLEADDRESSDETAILSFROMPLACEIDURLOLDAPI =  System.Label.GoogleAddressDetailsFromPlaceIdUrlOldAPI;
    public final static String GOOGLEAPIKEY = System.Label.GoogleAPIKey;
    public final static String GOOGLEADDRESSFROMLATLANG = System.Label.GoogleReverseGeocodingURL;
    
	public final static String RESULT = System.Label.result;
    public final static String RESULTS = System.Label.results;
    public final static String ROOFTOP = System.Label.ROOFTOP;
    public final static String RESULTTYPE = System.Label.street_address;
    public final static String ADDRESSCOMPONENTS = System.Label.address_components;
    public final static String TYPES = System.Label.types;
    public final static String ROUTE = System.Label.route;
    public final static String LONGNAME = System.Label.long_name;
    public final static String LOCALITY = System.Label.locality;
    public final static String CITY = System.Label.city;
    public final static String ADMINISTRATIVEAREALEVEL1 = System.Label.administrative_area_level_1;
    public final static String ADMINISTRATIVEAREALEVEL2 = System.Label.administrative_area_level_2;
    public final static String COUNTY = System.Label.county;
    public final static String COUNTRY = System.Label.country;
    public final static String POSTALCODE = System.Label.postal_code;
    public final static String STATE = System.Label.state;
    public final static String STREET = System.Label.street;
    public final static String UTF8 = System.Label.UTF_8;
    public final static String GETREQUEST = System.Label.GET;
    public final static String NONE = System.Label.None;
    public final static String FORMATTEDADDRESS = System.Label.formatted_address;
}