/* Class Name   : X11_Constants
 * Description  : Holds Constants for all the Lightning Community X11 Classes
 * Created By   : Abhishek Mishra
 * Created On   : 04-MAR-2019

 * Modification Log:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Developer                Date        Modification ID      Description 
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Abhishek Mishra          04-MAR-2019        1000            Initial version
 */
public class X11_Constants {
	Public static string sERROR = System.Label.Error_Label;
    Public static string sSUCCESS = System.Label.Success_Label;
    Public static string sPartnerProfileName = System.Label.Partner_Community_User;
    Public static string sSourceSystem = System.Label.Salesforce_X11_Lightning_Community;
    Public static string sCommunitySURL = System.Label.X11_Request_Service_Link;
    Public static string sType = System.Label.Application;
    Public static string sCountryCode = System.Label.CountryCode;
    Public static boolean bDuplicate_Rule_Blocker = false;
    Public static string sNoCaseConfig = System.Label.No_Case_Config;
    public static String sCustomerProfileName = System.Label.Guest_User_Profile;
    public static String ENABLE_CASE_TRIGGER = System.Label.ENABLE_CASE_TRIGGER;
    
    public static String EINSTEIN_MODELID_VALUE = 'GJN65CYHB3WH7ULLXHF27U6VJU'; 
}